# Basic information
baseURL = 'https://wxddo.github.io' # Should be updated to your domain
languageCode = 'en-us'
theme="archie"

# Metadata to edit
title = 'Willow Page Delp'
copyright = "© Willow Page Delp"
blogTitle='Check out my blog:'

# For code highlighting
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Social media for footer icons, could add more
[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://instagram.com/wxddo"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/wxddod"

# Menu items
[[menu.main]]
name = "home"
url = "/"
weight = 1 # lower number sorts them to the left

[[menu.main]]
name = "blog"
url = "/posts"
weight = 2

[[menu.main]]
name = "tags"
url = "/tags"
weight = 3
